#!/usr/bin/env python3
"""Regenerate docs/tools.md from the live Supero MCP server.

Needs no API key: tools/list answers an anonymous caller. Run it whenever the
server gains or changes a tool, and commit the result.

    python3 scripts/gen_tools_reference.py
"""
import json
import os
import sys
import urllib.request

ENDPOINT = os.environ.get("SUPERO_MCP_URL", "https://api.supero.dev/mcp/v1/messages")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "tools.md")

# Family -> (order, one-line purpose). Order is the order a build session meets them.
FAMILIES = {
    "build": (1, "Author, validate, publish, deploy and test a whole application"),
    "schema": (2, "List, validate, save and update object types"),
    "crud": (3, "Read and write records of any type"),
    "rbac": (4, "Ask what the current credential may do"),
    "apikey": (5, "Scope summary for the key making the call"),
    "project": (6, "Link schemas into a project"),
    "sdk": (7, "Generate and download client SDKs"),
    "connector": (8, "Drive external data sources: discovery, sync runs, connectivity tests"),
}


def fetch_tools():
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}}).encode()
    req = urllib.request.Request(ENDPOINT, data=body, method="POST", headers={
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "User-Agent": "supero-mcp-tools-reference/1.0",
    })
    raw = urllib.request.urlopen(req, timeout=60).read().decode()
    if raw.lstrip().startswith(("event:", "data:")):
        raw = "\n".join(l[5:].strip() for l in raw.splitlines() if l.startswith("data:"))
    return json.loads(raw)["result"]["tools"]


def first_sentence(text):
    text = " ".join((text or "").split())
    for stop in (". ", " - ", " — "):
        cut = text.find(stop)
        if 0 < cut < 220:
            return text[:cut + (1 if stop == ". " else 0)].rstrip(" -—")
    return text[:220] + ("…" if len(text) > 220 else "")


def args_cell(schema):
    props = (schema or {}).get("properties") or {}
    required = set((schema or {}).get("required") or [])
    if not props:
        return "none"
    return ", ".join(("**`%s`**" if name in required else "`%s`") % name for name in props)


def main():
    tools = fetch_tools()
    groups = {}
    for tool in tools:
        groups.setdefault(tool["name"].split("_")[0], []).append(tool)

    out = [
        "# Tool reference",
        "",
        "Every tool the Supero MCP server offers, generated from the live server's own",
        "`tools/list` answer by [`scripts/gen_tools_reference.py`](../scripts/gen_tools_reference.py).",
        "Do not edit this file by hand; re-run the script.",
        "",
        "**%d tools.** Required arguments are in bold. Your agent reads the full" % len(tools),
        "argument schemas itself when it connects; this page is the map for people.",
        "",
        "| Family | Tools | What it is for |",
        "|---|---|---|",
    ]
    ordered = sorted(groups, key=lambda f: FAMILIES.get(f, (99, ""))[0])
    for fam in ordered:
        out.append("| [`%s_`](#%s) | %d | %s |" % (fam, fam, len(groups[fam]), FAMILIES.get(fam, (99, ""))[1]))
    for fam in ordered:
        out += ["", "## %s" % fam, "", "| Tool | Arguments | What it does |", "|---|---|---|"]
        for tool in groups[fam]:
            desc = first_sentence(tool.get("description", "")).replace("|", "\\|")
            out.append("| `%s` | %s | %s |" % (tool["name"], args_cell(tool.get("inputSchema")), desc))
    with open(OUT, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s: %d tools in %d families" % (os.path.relpath(OUT), len(tools), len(groups)))


if __name__ == "__main__":
    sys.exit(main())
